version: "3.8"

services:
  sparkJob:
    build:
      context: .
    image: spark-etl-job:latest
    environment:
      JDBC_URL: "jdbc:redshift://clusterName.redshift.amazonaws.com:5439/dbName"
      S3_TEMP_DIR: "s3a://bucketName/folderName/"
      DB_USER: "awsuser"
      DB_PASSWORD: "secret"
      S3_ACCESS_KEY: "secret"
      S3_SECRET_KEY: "secret"
    ports:
      - "4041:4040"

  zeppelin:
    image: apache/zeppelin:0.10.0
    ports:
      - "8081:8080"